version: "3.9"
services:
  
  influxdb:
    image: "influxdb:1.8.1"
    environment:
      INFLUXDB_DB: "\"nbomber\""
    ports:
      - "8086:8086"

  grafana:
    image: "grafana/grafana:8.5.2"
    ports:
      - "3000:3000"
    depends_on:
      - "influxdb"